-- MySQL Script generated by MySQL Workbench
-- 05/02/16 20:57:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tool` DEFAULT CHARACTER SET utf8 ;
USE `tool` ;

-- -----------------------------------------------------
-- Table `tool`.`usercategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tool`.`usercategory` (
  `category_id` INT NOT NULL,
  `usercategory` MEDIUMTEXT NOT NULL,
  `usercategory_description` VARCHAR(256) NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `tool`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tool`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `salt` VARCHAR(256) NOT NULL,
  `category_category_id`  NOT NULL,
  PRIMARY KEY (`user_id`, `category_category_id`),
  INDEX `fk_users_category_idx` (`category_category_id` ASC),
  CONSTRAINT `fk_users_category`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `tool`.`usercategory` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tool`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tool`.`clients` (
  `client_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_firstname` MEDIUMTEXT NULL,
  `client_lastname` MEDIUMTEXT NULL,
  `client_address` VARCHAR(128) NULL,
  `client_zipcode` VARCHAR(16) NULL,
  `client_email` VARCHAR(128) NULL,
  `client_phone` VARCHAR(32) NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tool`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tool`.`modules` (
  `module_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `module_name` MEDIUMTEXT NOT NULL,
  `module_description` VARCHAR(128) NULL,
  PRIMARY KEY (`module_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tool`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tool`.`staff` (
  `staff_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `staff_firstname` MEDIUMTEXT NULL,
  `staff_lastname` MEDIUMTEXT NULL,
  `staff_address` VARCHAR(128) NULL,
  `staff_zipcode` VARCHAR(16) NULL,
  `staff_email` VARCHAR(128) NULL,
  `staff_phone` VARCHAR(32) NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tool`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tool`.`subscriptions` (
  `subscription_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `subscription_name` MEDIUMTEXT NOT NULL,
  `clients_client_id` INT UNSIGNED NOT NULL,
  `staff_staff_id` INT UNSIGNED NOT NULL,
  `modules_module_id` INT UNSIGNED NOT NULL,
  `users_user_id` INT UNSIGNED NOT NULL,
  `users_category_category_id`  NOT NULL,
  PRIMARY KEY (`subscription_id`, `clients_client_id`, `staff_staff_id`, `modules_module_id`, `users_user_id`, `users_category_category_id`),
  INDEX `fk_subscription_clients1_idx` (`clients_client_id` ASC),
  INDEX `fk_subscription_staff1_idx` (`staff_staff_id` ASC),
  INDEX `fk_subscriptions_modules1_idx` (`modules_module_id` ASC),
  INDEX `fk_subscriptions_users1_idx` (`users_user_id` ASC, `users_category_category_id` ASC),
  CONSTRAINT `fk_subscription_clients1`
    FOREIGN KEY (`clients_client_id`)
    REFERENCES `tool`.`clients` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_staff1`
    FOREIGN KEY (`staff_staff_id`)
    REFERENCES `tool`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscriptions_modules1`
    FOREIGN KEY (`modules_module_id`)
    REFERENCES `tool`.`modules` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscriptions_users1`
    FOREIGN KEY (`users_user_id` , `users_category_category_id`)
    REFERENCES `tool`.`users` (`user_id` , `category_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
